include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude: [build/**, lib/**.g.dart]
  plugins:
    - custom_lint

linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: false
