name: madcamp_week1
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_riverpod: ^2.4.9
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.9
  json_annotation: ^4.8.1
  url_launcher: ^6.2.2

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_lint: ^2.3.7
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: true
  image_path: 'images/logo.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'images/logo.png'

flutter:
  uses-material-design: true
  assets:
    - images/
